<?php

namespace Database\Seeders;

use App\Models\WorkOrder;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class WorkOrderSeeder extends Seeder
{
    public function run()
    {
        $workOrders = [

            // -----------------------------------------------------------------
            // 0) Tvoj originalni INTERSPORT primjer
            // -----------------------------------------------------------------
            [
                'work_order_number' => '#240100000005',
                'title'             => 'INTERSPORT Ltd Work Order',
                'description'       => 'Production batch for Metro order 2024.',
                'status'            => 'U toku',
                'priority'          => 'Z',
                'client_name'       => 'INTERSPORT Ltd.',
                'client_address'    => 'Korisnik 32, Sarajevo',
                'client_phone'      => '+387 33 123 456',
                'client_email'      => 'info@intersport.com',
                'recipient_name'    => 'Bingo d.o.o.',
                'recipient_address' => 'Grbavička 12, 71000 Sarajevo, B&H',
                'recipient_phone'   => '+387 33 789 012',
                'recipient_email'   => 'info@bingo.ba',
                'total'             => 0,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2024, 1, 25),
                'planned_end'       => Carbon::create(2024, 1, 27),
                'actual_start'      => Carbon::create(2024, 1, 25),
                'actual_end'        => null,
                'linked_document'   => 'DOC-2401',
                'created_by'        => 'Administrator',
                'notes'             => 'Sample data for local work order list',
            ],

            // -----------------------------------------------------------------
            // 1) 25-6000-003666 – KLAMMER
            // -----------------------------------------------------------------
            [
                'work_order_number' => '25-6000-003666',
                'title'             => 'KLAMMER – Trendy Germany GmbH-32',
                'description'       => 'Work order for part KLAMMER for Trendy Germany GmbH-32.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-32',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 10,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 10, 13, 14, 0),
                'planned_end'       => Carbon::create(2025, 10, 13, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001505',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 2) 25-6000-003836 – Mitnehmer
            [
                'work_order_number' => '25-6000-003836',
                'title'             => 'Mitnehmer – Trendy Germany GmbH-21',
                'description'       => 'Work order for Mitnehmer for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 1,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2026, 1, 12, 14, 0),
                'planned_end'       => Carbon::create(2026, 1, 12, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001568',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 3) 25-6000-003859 – Hülse
            [
                'work_order_number' => '25-6000-003859',
                'title'             => 'Hülse – Trendy Germany GmbH-21',
                'description'       => 'Work order for Hülse for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 1,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2026, 1, 19, 14, 0),
                'planned_end'       => Carbon::create(2026, 1, 19, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001568',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 4) 25-6000-003966 – Halter
            [
                'work_order_number' => '25-6000-003966',
                'title'             => 'Halter – Trendy Germany GmbH-21',
                'description'       => 'Work order for Halter for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 2,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 15, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 15, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001636',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 5) 25-6000-003967 – Platte
            [
                'work_order_number' => '25-6000-003967',
                'title'             => 'Platte – Trendy Germany GmbH-21',
                'description'       => 'Work order for Platte for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 2,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 15, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 15, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001636',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 6) 25-6000-004037 – Halter Y=16
            [
                'work_order_number' => '25-6000-004037',
                'title'             => 'Halter Y=16 assembly',
                'description'       => 'Halter Y=16 with detailed QA for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Electroplating & QA',
                'recipient_address' => 'Final inspection, Hemijack 5, Sarajevo',
                'recipient_phone'   => '+387 33 555 003',
                'recipient_email'   => 'qa@trendy.ba',
                'total'             => 2200,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2026, 1, 12, 14, 0),
                'planned_end'       => Carbon::create(2026, 1, 12, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001643',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 7) 25-6000-004038 – Anschlag
            [
                'work_order_number' => '25-6000-004038',
                'title'             => 'Anschlag – Trendy Germany GmbH-21',
                'description'       => 'Work order for Anschlag for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 2,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2026, 1, 12, 14, 0),
                'planned_end'       => Carbon::create(2026, 1, 12, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001643',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 8) 25-6000-004039 – Klotz
            [
                'work_order_number' => '25-6000-004039',
                'title'             => 'Klotz – Trendy Germany GmbH-21',
                'description'       => 'Work order for Klotz for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 4,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2026, 1, 19, 14, 0),
                'planned_end'       => Carbon::create(2026, 1, 19, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001643',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 9) 25-6000-004086 – Halter
            [
                'work_order_number' => '25-6000-004086',
                'title'             => 'Halter – Trendy Germany GmbH-21',
                'description'       => 'Additional Halter order for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 2,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2026, 1, 19, 14, 0),
                'planned_end'       => Carbon::create(2026, 1, 19, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001643',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 10) 25-6000-004102 – PASSRING
            [
                'work_order_number' => '25-6000-004102',
                'title'             => 'PASSRING – Trendy Germany-2',
                'description'       => 'Work order for PASSRING for Trendy Germany-2.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany-2',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 7,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 10, 13, 14, 0),
                'planned_end'       => Carbon::create(2025, 10, 13, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001697',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 11) 25-6000-004261 – Aufnahme Gleitschiene
            [
                'work_order_number' => '25-6000-004261',
                'title'             => 'Aufnahme Gleitschiene – Trendy Germany GmbH-32',
                'description'       => 'Work order for Aufnahme Gleitschiene for Trendy Germany GmbH-32.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-32',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 20,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 29, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 29, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001791',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 12) 25-6000-004274 – PASSFEDER 14X9X40
            [
                'work_order_number' => '25-6000-004274',
                'title'             => 'PASSFEDER 14X9X40 – Trendy Germany-2',
                'description'       => 'Work order for PASSFEDER 14X9X40 for Trendy Germany-2.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany-2',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 9,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 11, 10, 14, 0),
                'planned_end'       => Carbon::create(2025, 11, 10, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001812',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 13) 25-6000-004305 – MITNEHMER
            [
                'work_order_number' => '25-6000-004305',
                'title'             => 'MITNEHMER – Trendy Germany-2',
                'description'       => 'Work order for MITNEHMER for Trendy Germany-2.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany-2',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 6,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 10, 13, 14, 0),
                'planned_end'       => Carbon::create(2025, 10, 13, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001832',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 14) 25-6000-004314 – KANAL LANG
            [
                'work_order_number' => '25-6000-004314',
                'title'             => 'KANAL LANG – Trendy Germany GmbH-32',
                'description'       => 'Work order for KANAL LANG for Trendy Germany GmbH-32.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-32',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 25,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 8, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 8, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001753',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 15) 25-6000-004341 – Platte
            [
                'work_order_number' => '25-6000-004341',
                'title'             => 'Platte – Trendy Germany GmbH-21',
                'description'       => 'Work order for Platte for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 1,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 22, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 22, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001852',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 16) 25-6000-004342 – Platte
            [
                'work_order_number' => '25-6000-004342',
                'title'             => 'Platte – Trendy Germany GmbH-21 (druga pozicija)',
                'description'       => 'Second Platte position for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 1,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 22, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 22, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001852',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 17) 25-6000-004347 – Platte GM5314/01-60-141/1-1-70-1
            [
                'work_order_number' => '25-6000-004347',
                'title'             => 'Platte GM5314/01-60-141/1-1-70-1 – GROB-WERKE',
                'description'       => 'Work order for Platte GM5314/01-60-141/1-1-70-1 for GROB-WERKE.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'GROB-WERKE',
                'client_address'    => 'Industriestr. 4, 87700 Mindelheim, Germany',
                'client_phone'      => '+49 8261 962 0',
                'client_email'      => 'info@grob.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 4,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 10, 14, 14, 0),
                'planned_end'       => Carbon::create(2025, 10, 14, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001854',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 18) 25-6000-004348 – Platte GM5314/01-60-141/1-1-70-1 (drugi set)
            [
                'work_order_number' => '25-6000-004348',
                'title'             => 'Platte GM5314/01-60-141/1-1-70-1 – GROB-WERKE (drugi set)',
                'description'       => 'Second work order for Platte GM5314/01-60-141/1-1-70-1 for GROB-WERKE.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'GROB-WERKE',
                'client_address'    => 'Industriestr. 4, 87700 Mindelheim, Germany',
                'client_phone'      => '+49 8261 962 0',
                'client_email'      => 'info@grob.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 3,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 11, 7, 14, 0),
                'planned_end'       => Carbon::create(2025, 11, 7, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001854',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 19) 25-6000-004360 – Platte (DS01A17020)
            [
                'work_order_number' => '25-6000-004360',
                'title'             => 'Platte – Trendy Germany GmbH-45',
                'description'       => 'Work order for Platte for Trendy Germany GmbH-45.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-45',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 10,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 15, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 15, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001862',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 20) 25-6000-004389 – Klotz GM5314/01-60-141/1-1-70-7
            [
                'work_order_number' => '25-6000-004389',
                'title'             => 'Klotz GM5314/01-60-141/1-1-70-7 – GROB-WERKE',
                'description'       => 'Work order for Klotz GM5314/01-60-141/1-1-70-7 for GROB-WERKE.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'GROB-WERKE',
                'client_address'    => 'Industriestr. 4, 87700 Mindelheim, Germany',
                'client_phone'      => '+49 8261 962 0',
                'client_email'      => 'info@grob.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 15,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 10, 15, 14, 0),
                'planned_end'       => Carbon::create(2025, 10, 15, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001888',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 21) 25-6000-004398 – Klotz GS16-1985-0100-04-10-44
            [
                'work_order_number' => '25-6000-004398',
                'title'             => 'Klotz GS16-1985-0100-04-10-44 – GROB-WERKE',
                'description'       => 'Work order for Klotz GS16-1985-0100-04-10-44 for GROB-WERKE.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'GROB-WERKE',
                'client_address'    => 'Industriestr. 4, 87700 Mindelheim, Germany',
                'client_phone'      => '+49 8261 962 0',
                'client_email'      => 'info@grob.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 12,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 24, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 24, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001888',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 22) 25-6000-004399 – Klotz GS26-1985-0100-03-10-44
            [
                'work_order_number' => '25-6000-004399',
                'title'             => 'Klotz GS26-1985-0100-03-10-44 – GROB-WERKE',
                'description'       => 'Work order for Klotz GS26-1985-0100-03-10-44 for GROB-WERKE.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'GROB-WERKE',
                'client_address'    => 'Industriestr. 4, 87700 Mindelheim, Germany',
                'client_phone'      => '+49 8261 962 0',
                'client_email'      => 'info@grob.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 5,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 24, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 24, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001888',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 23) 25-6000-004414 – Bolzen L=50
            [
                'work_order_number' => '25-6000-004414',
                'title'             => 'Bolzen L=50 – Trendy Germany GmbH-21',
                'description'       => 'Work order for Bolzen L=50 for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 6,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 22, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 22, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001852',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 24) 25-6000-004415 – Bolzen L=40
            [
                'work_order_number' => '25-6000-004415',
                'title'             => 'Bolzen L=40 – Trendy Germany GmbH-21',
                'description'       => 'Work order for Bolzen L=40 for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 8,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 8, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 8, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001914',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 25) 25-6000-004420 – Lagerbock
            [
                'work_order_number' => '25-6000-004420',
                'title'             => 'Lagerbock – Trendy Germany GmbH-21',
                'description'       => 'Work order for Lagerbock for Trendy Germany GmbH-21.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'Trendy Germany GmbH-21',
                'client_address'    => 'Am Trendpark 2, 73054 Suhl, Germany',
                'client_phone'      => '+49 3601 123 47',
                'client_email'      => 'orders@trendy-germany.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 30,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 16, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 16, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001925',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

            // 26) 25-6000-004425 – Platte G751-1200-0000-01-4
            [
                'work_order_number' => '25-6000-004425',
                'title'             => 'Platte G751-1200-0000-01-4 – GROB-WERKE',
                'description'       => 'Work order for Platte G751-1200-0000-01-4 for GROB-WERKE.',
                'status'            => 'Planiran',
                'priority'          => '5 - Uobičajeni prioritet',
                'client_name'       => 'GROB-WERKE',
                'client_address'    => 'Industriestr. 4, 87700 Mindelheim, Germany',
                'client_phone'      => '+49 8261 962 0',
                'client_email'      => 'info@grob.de',
                'recipient_name'    => 'Main production line',
                'recipient_address' => 'Plant 1, Sarajevo',
                'recipient_phone'   => '+387 33 555 000',
                'recipient_email'   => 'production@trendy.ba',
                'total'             => 6,
                'currency'          => 'EUR',
                'planned_start'     => Carbon::create(2025, 9, 16, 14, 0),
                'planned_end'       => Carbon::create(2025, 9, 16, 14, 0),
                'actual_start'      => null,
                'actual_end'        => null,
                'linked_document'   => '25-0110-001925',
                'created_by'        => 'System Import',
                'notes'             => 'Imported from Pantheon work order list',
            ],

        ];

        foreach ($workOrders as $order) {
            WorkOrder::updateOrCreate(
                ['work_order_number' => $order['work_order_number']],
                $order
            );
        }
    }
}
