<?php

return [
    'schema' => env('DB_SCHEMA', 'dbo'),
    'table' => env('WORK_ORDERS_TABLE', 'tHF_WOEx'),
    'items_table' => env('WORK_ORDER_ITEMS_TABLE', 'tHF_WOExItem'),
    'catalog_items_table' => env('WORK_ORDER_CATALOG_ITEMS_TABLE', 'tHE_SetItem'),
    'stock_table' => env('WORK_ORDER_STOCK_TABLE', 'tHE_Stock'),
    'item_resources_table' => env('WORK_ORDER_ITEM_RESOURCES_TABLE', 'tHF_WOExItemResources'),
    'reg_operations_table' => env('WORK_ORDER_REG_OPER_TABLE', 'tHF_WOExRegOper'),
    'product_structure_table' => env('WORK_ORDER_PRODUCT_STRUCTURE_TABLE', 'tHF_SetPrSt'),
    'orders_table' => env('WORK_ORDER_ORDERS_TABLE', 'tHE_Order'),
    'order_items_table' => env('WORK_ORDER_ORDER_ITEMS_TABLE', 'tHE_OrderItem'),
    'work_order_order_item_link_table' => env('WORK_ORDER_ORDER_ITEM_LINK_TABLE', 'vHF_LinkWOExOrderItem'),
    'work_order_order_item_link_insert_table' => env('WORK_ORDER_ORDER_ITEM_LINK_INSERT_TABLE', 'tHF_LinkWOExOrderItem'),
    'order_item_move_link_table' => env('WORK_ORDER_ORDER_ITEM_MOVE_LINK_TABLE', 'tHE_LinkMoveItemOrderItem'),
    'move_items_table' => env('WORK_ORDER_MOVE_ITEMS_TABLE', 'tHE_MoveItem'),
    'catalog_product_defaults' => [
        'vat_code' => env('WORK_ORDER_CATALOG_DEFAULT_VAT_CODE', 'P1'),
        'vat_rate' => (float) env('WORK_ORDER_CATALOG_DEFAULT_VAT_RATE', 17),
        'currency' => env('WORK_ORDER_CATALOG_DEFAULT_CURRENCY', 'KM'),
        'purchase_currency' => env('WORK_ORDER_CATALOG_DEFAULT_PURCHASE_CURRENCY', 'KM'),
        'production_doc_type' => env('WORK_ORDER_CATALOG_DEFAULT_PRODUCTION_DOC_TYPE', '6000'),
        'unit_dimension_2' => env('WORK_ORDER_CATALOG_DEFAULT_UNIT_DIMENSION_2', 'KG'),
        'delivery_deadline' => (int) env('WORK_ORDER_CATALOG_DEFAULT_DELIVERY_DEADLINE', 7),
        'allowed_inv_short' => (float) env('WORK_ORDER_CATALOG_DEFAULT_ALLOWED_INV_SHORT', -1),
        'prst_optimal_qty' => (float) env('WORK_ORDER_CATALOG_DEFAULT_PRST_OPTIMAL_QTY', 0),
        'prst_daily_qty' => (float) env('WORK_ORDER_CATALOG_DEFAULT_PRST_DAILY_QTY', 0),
    ],
    'pantheon_user_map' => [],
    'default_limit' => 10,
    'max_limit' => 100,
    'bom_limit' => 100,
];
