<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Support\Carbon; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Log;
class ProductionPlanController extends Controller {
 private function admin($u):bool{return $u&&method_exists($u,'isAdmin')?$u->isAdmin():strtolower(trim((string)($u->role??'')))==='admin';}
 public function index(Request $r){return view('content.apps.production.app-production-plan',['pageConfigs'=>['pageHeader'=>false],'planConfig'=>['dataUrl'=>route('app-production-plan-data'),'operationsUrl'=>route('app-production-plan-operations',['id'=>'__RN__']),'fieldUrl'=>route('app-production-plan-field',['id'=>'__RN__']),'previewUrl'=>route('app-invoice-preview',['id'=>'__RN__']),'canEdit'=>$this->admin($r->user())]]);}
 public function data(Request $r){try{$f=(array)$r->input('filter',[]);$s=config('workorders.schema','dbo');$status="UPPER(LTRIM(RTRIM(wo.acStatusMF)))";$q=DB::table($s.'.tHF_WOEx as wo')->selectRaw("wo.acKey id,wo.acKeyView rn,ISNULL(wo.acConsignee,wo.acReceiver) narucitelj,wo.anPriority prioritet,CAST(wo.adDate AS date) datum,wo.acLnkKeyView narudzba,wo.anLnkNo pozicija,wo.adSchedStartTime pocetak,wo.adSchedEndTime kraj,wo.acIdent proizvod,wo.anPlanQty plan_kol,wo.anProducedQty izr_kol,wo.acName naziv,wo.acNote napomena,CASE $status WHEN 'D' THEN N'Raspisan' WHEN 'O' THEN N'Otvoren' WHEN 'E' THEN N'U radu' WHEN 'P' THEN N'U toku' WHEN 'R' THEN N'Djelomično zaključen' WHEN 'F' THEN N'Zaključen' WHEN 'I' THEN N'Zaključen' WHEN 'Z' THEN N'Zaključen' WHEN 'N' THEN N'Novo' ELSE N'Nedefinisan' END status_rn");$map=['rn'=>'wo.acKeyView','narucitelj'=>'wo.acConsignee','proizvod'=>'wo.acIdent','status_rn'=>'wo.acStatusMF','narudzba'=>'wo.acLnkKeyView'];foreach($map as $k=>$col)if(($v=trim((string)($f[$k]??'')))!=='')$q->where($col,'like','%'.$v.'%');foreach([['datum_od','>='],['datum_do','<=']] as [$k,$op])if(($v=trim((string)($f[$k]??'')))!=='')$q->whereDate('wo.adDate',$op,$v);if(($w=(int)($f['kw']??0))&&($y=(int)($f['year']??0))){$d=Carbon::now()->setISODate($y,$w)->startOfWeek();$q->whereDate('wo.adDate','>=',$d)->whereDate('wo.adDate','<=',$d->copy()->endOfWeek());}$total=(clone $q)->count();$sorts=['rn'=>'wo.acKeyView','narucitelj'=>'wo.acConsignee','prioritet'=>'wo.anPriority','datum'=>'wo.adDate','narudzba'=>'wo.acLnkKeyView','pozicija'=>'wo.anLnkNo','pocetak'=>'wo.adSchedStartTime','kraj'=>'wo.adSchedEndTime','proizvod'=>'wo.acIdent','plan_kol'=>'wo.anPlanQty','izr_kol'=>'wo.anProducedQty','naziv'=>'wo.acName','napomena'=>'wo.acNote'];$sort=$sorts[$r->input('sort','datum')]??'wo.adDate';$dir=$r->input('dir')==='asc'?'asc':'desc';$rows=$q->orderBy($sort,$dir)->offset(max(0,(int)$r->input('start',0)))->limit(min(100,max(10,(int)$r->input('length',25))))->get();$keys=$rows->pluck('id');$tot=DB::table($s.'.tHF_WOExRegOper')->whereIn('acKey',$keys)->selectRaw('acKey,COUNT(*) n')->groupBy('acKey')->pluck('n','acKey');$done=DB::table($s.'.tHF_WOExItem')->whereIn('acKey',$keys)->whereIn('acTaskState',['F','Z','C','D'])->selectRaw('acKey,COUNT(*) n')->groupBy('acKey')->pluck('n','acKey');foreach($rows as $x)$x->progress=($tot[$x->id]??0)?min(100,round(($done[$x->id]??0)/$tot[$x->id]*100)):0;return response()->json(['draw'=>(int)$r->input('draw',0),'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$rows]);}catch(\Throwable $e){Log::error('RN plan error',['message'=>$e->getMessage()]);return response()->json(['message'=>'Greška pri učitavanju plana proizvodnje.'],500);}}
 public function updateField(Request $r,string $id){if(!$this->admin($r->user()))return response()->json(['message'=>'Nemate dozvolu za izmjene.'],403);$map=['narucitelj'=>'acConsignee','prioritet'=>'anPriority','datum'=>'adDate','narudzba'=>'acLnkKeyView','pozicija'=>'anLnkNo','pocetak'=>'adSchedStartTime','kraj'=>'adSchedEndTime','proizvod'=>'acIdent','plan_kol'=>'anPlanQty','izr_kol'=>'anProducedQty','naziv'=>'acName','napomena'=>'acNote'];$field=(string)$r->input('field');if(!isset($map[$field]))return response()->json(['message'=>'Polje nije dozvoljeno.'],422);DB::table(config('workorders.schema','dbo').'.tHF_WOEx')->where('acKey',$id)->update([$map[$field]=>$r->input('value'),'adTimeChg'=>now(),'anUserChg'=>(int)$r->user()->id]);return response()->json(['message'=>'Sačuvano.']);}
 public function operations(string $id){return response()->json(['data'=>[]]);}
}
